# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Gradle Plugins
kotlin_version=2.2.20
loom_version=1.11-SNAPSHOT
grgit_version=5.0.0
cursegradle_version=1.4.0
modrinth_version=2.8.7
github_api_version=1.314

# Mod Properties
mod_version=2.0-BETA+1.21
maven_group=io.github.lucaargolo
loom.platform = neoforge

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2
yarn_mappings_patch_version=1.21+build.4

#Fabric api
neoforge_version=21.1.209
fabric_version=0.115.6+2.1.3+1.21.1
kotlin_forge_version=5.10.0

# Libraries
pal_version=1.10.0
curios_version=9.5.1+1.21.1
rei_version=16.0.799

# Publishing
curseforge_id=388832
modrinth_id=OvlwmUdC