modLoader = "kotlinforforge" #mandatory
loaderVersion = "[5.10,)" #mandatory
license = "Mozilla Public License 2.0"

[[mods]] #mandatory
modId = "kibe" #mandatory
version = "${version}" #mandatory
displayName = "Kibe" #mandatory
authors = "D4rkness_King" #optional
logoFile="assets/kibe/icon.png"
description = '''A miscellaneous mod that adds a bunch of random, and mostly unoriginal things.'''

[[dependencies.kibe]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kibe]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "kibe.mixins.json"
